welcomeText = "Startpage!"
startPageColumns = true

[[searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"

[[searchEngines]]
  name = "Google for WordPress Info"
  activated = true
  url = "https://cse.google.com/cse?cx=011006674894885990812:lxe4cdk4owr&q="

[[searchEngines]]
  name = "Google for TamperMonkey userscripts"
  activated = true
  url = "https://cse.google.com/cse?cx=011006674894885990812:x5wimeati0y"
